//! The declarative schema DSL. A [`PgTableSpec`] is the single source of truth;
//! everything else the kit produces is derived from it.
//!
//! The DSL is builder-style and total: a column, table, enum, view, sequence,
//! role, foreign key, unique/check constraint, index, generated/identity column,
//! composite primary key, RLS toggle, and row-level policy can all be expressed
//! here. From this set you derive `CREATE TABLE` DDL ([`crate::to_create_table_sql`])
//! and the diffable [`crate::differ::SchemaSnapshot`] ([`crate::differ::lower`]).

/// A Postgres column type. The closed set keeps DDL generation total and the
/// future differ/codegen exhaustive. `Enum` names a user-defined enum type;
/// `Array` wraps any inner type.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum PgType {
    Uuid,
    Text,
    Varchar(Option<u32>),
    Bool,
    Int2,
    Int4,
    Int8,
    Float4,
    Float8,
    Numeric(Option<(u32, u32)>),
    Timestamptz,
    Timestamp,
    Date,
    Jsonb,
    Json,
    Bytea,
    /// Full-text search vector (`tsvector`).
    Tsvector,
    /// A pgvector embedding column. `Vector(None)` renders `vector`; `Vector(Some(n))`
    /// renders `vector(n)` (fixed-dimension).
    Vector(Option<u32>),
    /// A named Postgres enum type (e.g. `CREATE TYPE managed_website_status AS ENUM (...)`).
    Enum(String),
    /// An array of the inner type, rendered as `<inner>[]`.
    Array(Box<PgType>),
}

impl PgType {
    /// Render the canonical Postgres type text.
    pub fn to_sql_type(&self) -> String {
        match self {
            PgType::Uuid => "uuid".into(),
            PgType::Text => "text".into(),
            PgType::Varchar(None) => "varchar".into(),
            PgType::Varchar(Some(n)) => format!("varchar({n})"),
            PgType::Bool => "boolean".into(),
            PgType::Int2 => "smallint".into(),
            PgType::Int4 => "integer".into(),
            PgType::Int8 => "bigint".into(),
            PgType::Float4 => "real".into(),
            PgType::Float8 => "double precision".into(),
            PgType::Numeric(None) => "numeric".into(),
            PgType::Numeric(Some((p, s))) => format!("numeric({p},{s})"),
            PgType::Timestamptz => "timestamptz".into(),
            PgType::Timestamp => "timestamp".into(),
            PgType::Date => "date".into(),
            PgType::Jsonb => "jsonb".into(),
            PgType::Json => "json".into(),
            PgType::Bytea => "bytea".into(),
            PgType::Tsvector => "tsvector".into(),
            PgType::Vector(None) => "vector".into(),
            PgType::Vector(Some(n)) => format!("vector({n})"),
            PgType::Enum(name) => name.clone(),
            PgType::Array(inner) => format!("{}[]", inner.to_sql_type()),
        }
    }
}

/// A referential action for foreign-key `ON UPDATE` / `ON DELETE`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ReferentialAction {
    NoAction,
    Restrict,
    Cascade,
    SetNull,
    SetDefault,
}

impl ReferentialAction {
    /// Render the SQL keyword form (e.g. `SET NULL`).
    pub fn to_sql(self) -> &'static str {
        match self {
            ReferentialAction::NoAction => "NO ACTION",
            ReferentialAction::Restrict => "RESTRICT",
            ReferentialAction::Cascade => "CASCADE",
            ReferentialAction::SetNull => "SET NULL",
            ReferentialAction::SetDefault => "SET DEFAULT",
        }
    }
}

/// Whether an identity column is `GENERATED ALWAYS` or `GENERATED BY DEFAULT`.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Default)]
pub enum IdentityKind {
    Always,
    #[default]
    ByDefault,
}

impl IdentityKind {
    pub fn to_sql(self) -> &'static str {
        match self {
            IdentityKind::Always => "ALWAYS",
            IdentityKind::ByDefault => "BY DEFAULT",
        }
    }
}

/// Sequence shaping options, shared by standalone sequences and identity columns.
/// All fields are optional verbatim numeric strings (trusted, developer-authored).
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct SequenceOptions {
    pub increment: Option<String>,
    pub min_value: Option<String>,
    pub max_value: Option<String>,
    pub start_with: Option<String>,
    pub cache: Option<String>,
    pub cycle: bool,
}

impl SequenceOptions {
    pub fn new() -> Self {
        Self::default()
    }
    pub fn increment(mut self, v: impl Into<String>) -> Self {
        self.increment = Some(v.into());
        self
    }
    pub fn min_value(mut self, v: impl Into<String>) -> Self {
        self.min_value = Some(v.into());
        self
    }
    pub fn max_value(mut self, v: impl Into<String>) -> Self {
        self.max_value = Some(v.into());
        self
    }
    pub fn start_with(mut self, v: impl Into<String>) -> Self {
        self.start_with = Some(v.into());
        self
    }
    pub fn cache(mut self, v: impl Into<String>) -> Self {
        self.cache = Some(v.into());
        self
    }
    pub fn cycle(mut self, on: bool) -> Self {
        self.cycle = on;
        self
    }
}

/// An identity column declaration (`GENERATED {ALWAYS|BY DEFAULT} AS IDENTITY`).
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct IdentitySpec {
    pub kind: IdentityKind,
    pub sequence: SequenceOptions,
}

impl IdentitySpec {
    pub fn always() -> Self {
        Self {
            kind: IdentityKind::Always,
            sequence: SequenceOptions::default(),
        }
    }
    pub fn by_default() -> Self {
        Self {
            kind: IdentityKind::ByDefault,
            sequence: SequenceOptions::default(),
        }
    }
    pub fn with_sequence(mut self, seq: SequenceOptions) -> Self {
        self.sequence = seq;
        self
    }
}

/// A `GENERATED ALWAYS AS (<expr>) STORED` column. The expression is verbatim,
/// trusted, developer-authored input.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct GeneratedColumn {
    pub expression: String,
}

/// Column-level uniqueness (`UNIQUE` / `UNIQUE NULLS NOT DISTINCT`).
#[derive(Debug, Clone, PartialEq, Eq, Default)]
pub struct ColumnUnique {
    /// Optional explicit constraint name.
    pub name: Option<String>,
    pub nulls_not_distinct: bool,
}

/// A single column. Construct with [`ColumnSpec::new`] and chain the builder
/// helpers (`.nullable()`, `.default_expr(...)`, `.generated_stored(...)`, …).
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ColumnSpec {
    pub name: String,
    pub ty: PgType,
    pub nullable: bool,
    /// A trusted, developer-authored default expression (emitted verbatim).
    pub default: Option<String>,
    /// A `STORED` generated column expression, if any.
    pub generated: Option<GeneratedColumn>,
    /// An identity declaration, if any.
    pub identity: Option<IdentitySpec>,
    /// Column-level uniqueness, if any.
    pub unique: Option<ColumnUnique>,
}

impl ColumnSpec {
    pub fn new(name: impl Into<String>, ty: PgType) -> Self {
        Self {
            name: name.into(),
            ty,
            nullable: false,
            default: None,
            generated: None,
            identity: None,
            unique: None,
        }
    }

    pub fn nullable(mut self) -> Self {
        self.nullable = true;
        self
    }

    pub fn default_expr(mut self, expr: impl Into<String>) -> Self {
        self.default = Some(expr.into());
        self
    }

    /// Mark this column as a `STORED` generated column.
    pub fn generated_stored(mut self, expr: impl Into<String>) -> Self {
        self.generated = Some(GeneratedColumn {
            expression: expr.into(),
        });
        self
    }

    /// Attach an identity declaration.
    pub fn identity(mut self, identity: IdentitySpec) -> Self {
        self.identity = Some(identity);
        self
    }

    pub fn identity_always(self) -> Self {
        self.identity(IdentitySpec::always())
    }

    pub fn identity_by_default(self) -> Self {
        self.identity(IdentitySpec::by_default())
    }

    /// Mark the column `UNIQUE`.
    pub fn unique(mut self) -> Self {
        self.unique = Some(ColumnUnique::default());
        self
    }

    /// Mark the column `UNIQUE` with an explicit constraint name.
    pub fn unique_named(mut self, name: impl Into<String>) -> Self {
        self.unique = Some(ColumnUnique {
            name: Some(name.into()),
            nulls_not_distinct: false,
        });
        self
    }
}

/// A foreign-key constraint.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ForeignKeySpec {
    pub name: String,
    pub columns_from: Vec<String>,
    /// The referenced table, optionally schema-qualified (`schema.table`).
    pub table_to: String,
    pub columns_to: Vec<String>,
    pub on_update: Option<ReferentialAction>,
    pub on_delete: Option<ReferentialAction>,
}

impl ForeignKeySpec {
    pub fn new(
        name: impl Into<String>,
        columns_from: impl IntoIterator<Item = impl Into<String>>,
        table_to: impl Into<String>,
        columns_to: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        Self {
            name: name.into(),
            columns_from: columns_from.into_iter().map(Into::into).collect(),
            table_to: table_to.into(),
            columns_to: columns_to.into_iter().map(Into::into).collect(),
            on_update: None,
            on_delete: None,
        }
    }

    pub fn on_update(mut self, action: ReferentialAction) -> Self {
        self.on_update = Some(action);
        self
    }

    pub fn on_delete(mut self, action: ReferentialAction) -> Self {
        self.on_delete = Some(action);
        self
    }
}

/// A table-level unique constraint.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UniqueConstraintSpec {
    pub name: String,
    pub columns: Vec<String>,
    pub nulls_not_distinct: bool,
}

impl UniqueConstraintSpec {
    pub fn new(
        name: impl Into<String>,
        columns: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        Self {
            name: name.into(),
            columns: columns.into_iter().map(Into::into).collect(),
            nulls_not_distinct: false,
        }
    }

    pub fn nulls_not_distinct(mut self) -> Self {
        self.nulls_not_distinct = true;
        self
    }
}

/// A `CHECK` constraint. `value` is a trusted, developer-authored expression.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct CheckConstraintSpec {
    pub name: String,
    pub value: String,
}

impl CheckConstraintSpec {
    pub fn new(name: impl Into<String>, value: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            value: value.into(),
        }
    }
}

/// One column (or expression) participating in an index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexColumn {
    /// Column name, or a raw expression when `is_expression` is true.
    pub expression: String,
    pub is_expression: bool,
    pub asc: bool,
    /// `NULLS FIRST` / `NULLS LAST`, if specified.
    pub nulls: Option<String>,
    /// Operator class, if specified.
    pub opclass: Option<String>,
}

impl IndexColumn {
    /// A plain ascending column reference.
    pub fn column(name: impl Into<String>) -> Self {
        Self {
            expression: name.into(),
            is_expression: false,
            asc: true,
            nulls: None,
            opclass: None,
        }
    }

    /// A raw expression index member (e.g. `lower(email)`).
    pub fn expr(expr: impl Into<String>) -> Self {
        Self {
            expression: expr.into(),
            is_expression: true,
            asc: true,
            nulls: None,
            opclass: None,
        }
    }

    pub fn desc(mut self) -> Self {
        self.asc = false;
        self
    }

    pub fn nulls(mut self, nulls: impl Into<String>) -> Self {
        self.nulls = Some(nulls.into());
        self
    }

    pub fn opclass(mut self, opclass: impl Into<String>) -> Self {
        self.opclass = Some(opclass.into());
        self
    }
}

/// A (possibly partial / unique / expression) index.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndexSpec {
    pub name: String,
    pub columns: Vec<IndexColumn>,
    pub unique: bool,
    /// Access method (`btree`, `gin`, …). Defaults to `btree`.
    pub method: String,
    /// A partial-index `WHERE` predicate (trusted expression).
    pub where_clause: Option<String>,
}

impl IndexSpec {
    pub fn new(name: impl Into<String>, columns: impl IntoIterator<Item = IndexColumn>) -> Self {
        Self {
            name: name.into(),
            columns: columns.into_iter().collect(),
            unique: false,
            method: "btree".into(),
            where_clause: None,
        }
    }

    pub fn unique(mut self) -> Self {
        self.unique = true;
        self
    }

    pub fn method(mut self, method: impl Into<String>) -> Self {
        self.method = method.into();
        self
    }

    pub fn where_clause(mut self, predicate: impl Into<String>) -> Self {
        self.where_clause = Some(predicate.into());
        self
    }
}

/// The `AS` permissiveness of a row-level-security policy.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolicyAs {
    Permissive,
    Restrictive,
}

impl PolicyAs {
    pub fn to_sql(self) -> &'static str {
        match self {
            PolicyAs::Permissive => "PERMISSIVE",
            PolicyAs::Restrictive => "RESTRICTIVE",
        }
    }
}

/// The command a policy applies to.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum PolicyFor {
    All,
    Select,
    Insert,
    Update,
    Delete,
}

impl PolicyFor {
    pub fn to_sql(self) -> &'static str {
        match self {
            PolicyFor::All => "ALL",
            PolicyFor::Select => "SELECT",
            PolicyFor::Insert => "INSERT",
            PolicyFor::Update => "UPDATE",
            PolicyFor::Delete => "DELETE",
        }
    }
}

/// A row-level-security policy on a table.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PolicySpec {
    pub name: String,
    pub as_: Option<PolicyAs>,
    pub for_: Option<PolicyFor>,
    /// Roles the policy applies `TO`.
    pub to: Vec<String>,
    /// The `USING` predicate (trusted expression).
    pub using: Option<String>,
    /// The `WITH CHECK` predicate (trusted expression).
    pub with_check: Option<String>,
}

impl PolicySpec {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            as_: None,
            for_: None,
            to: Vec::new(),
            using: None,
            with_check: None,
        }
    }

    pub fn as_permissiveness(mut self, as_: PolicyAs) -> Self {
        self.as_ = Some(as_);
        self
    }

    pub fn for_command(mut self, for_: PolicyFor) -> Self {
        self.for_ = Some(for_);
        self
    }

    pub fn to_roles(mut self, roles: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.to = roles.into_iter().map(Into::into).collect();
        self
    }

    pub fn using(mut self, predicate: impl Into<String>) -> Self {
        self.using = Some(predicate.into());
        self
    }

    pub fn with_check(mut self, predicate: impl Into<String>) -> Self {
        self.with_check = Some(predicate.into());
        self
    }
}

/// A table declaration — the unit of the schema source of truth.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct PgTableSpec {
    /// The containing schema. Defaults to `public`.
    pub schema: String,
    pub name: String,
    pub columns: Vec<ColumnSpec>,
    pub primary_key: Vec<String>,
    pub foreign_keys: Vec<ForeignKeySpec>,
    pub unique_constraints: Vec<UniqueConstraintSpec>,
    pub check_constraints: Vec<CheckConstraintSpec>,
    pub indexes: Vec<IndexSpec>,
    pub policies: Vec<PolicySpec>,
    pub rls_enabled: bool,
}

impl PgTableSpec {
    pub fn new(name: impl Into<String>, columns: Vec<ColumnSpec>) -> Self {
        Self {
            schema: "public".into(),
            name: name.into(),
            columns,
            primary_key: Vec::new(),
            foreign_keys: Vec::new(),
            unique_constraints: Vec::new(),
            check_constraints: Vec::new(),
            indexes: Vec::new(),
            policies: Vec::new(),
            rls_enabled: false,
        }
    }

    /// Place the table in a non-`public` schema.
    pub fn in_schema(mut self, schema: impl Into<String>) -> Self {
        self.schema = schema.into();
        self
    }

    pub fn primary_key(mut self, cols: impl IntoIterator<Item = impl Into<String>>) -> Self {
        self.primary_key = cols.into_iter().map(Into::into).collect();
        self
    }

    pub fn foreign_key(mut self, fk: ForeignKeySpec) -> Self {
        self.foreign_keys.push(fk);
        self
    }

    pub fn unique_constraint(mut self, uc: UniqueConstraintSpec) -> Self {
        self.unique_constraints.push(uc);
        self
    }

    pub fn check(mut self, cc: CheckConstraintSpec) -> Self {
        self.check_constraints.push(cc);
        self
    }

    pub fn index(mut self, idx: IndexSpec) -> Self {
        self.indexes.push(idx);
        self
    }

    pub fn policy(mut self, policy: PolicySpec) -> Self {
        self.policies.push(policy);
        self
    }

    pub fn enable_rls(mut self) -> Self {
        self.rls_enabled = true;
        self
    }

    /// The `schema.table` key used as the snapshot identity.
    pub fn qualified_name(&self) -> String {
        format!("{}.{}", self.schema, self.name)
    }
}

/// A top-level user-defined enum type declaration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct EnumTypeSpec {
    pub schema: String,
    pub name: String,
    pub values: Vec<String>,
}

impl EnumTypeSpec {
    pub fn new(
        name: impl Into<String>,
        values: impl IntoIterator<Item = impl Into<String>>,
    ) -> Self {
        Self {
            schema: "public".into(),
            name: name.into(),
            values: values.into_iter().map(Into::into).collect(),
        }
    }

    pub fn in_schema(mut self, schema: impl Into<String>) -> Self {
        self.schema = schema.into();
        self
    }

    pub fn qualified_name(&self) -> String {
        format!("{}.{}", self.schema, self.name)
    }
}

/// A (materialized) view declaration. `definition` is the trusted SELECT body.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ViewSpec {
    pub schema: String,
    pub name: String,
    pub definition: Option<String>,
    pub materialized: bool,
}

impl ViewSpec {
    pub fn new(name: impl Into<String>, definition: impl Into<String>) -> Self {
        Self {
            schema: "public".into(),
            name: name.into(),
            definition: Some(definition.into()),
            materialized: false,
        }
    }

    pub fn in_schema(mut self, schema: impl Into<String>) -> Self {
        self.schema = schema.into();
        self
    }

    pub fn materialized(mut self) -> Self {
        self.materialized = true;
        self
    }

    pub fn qualified_name(&self) -> String {
        format!("{}.{}", self.schema, self.name)
    }
}

/// A standalone sequence declaration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SequenceSpec {
    pub schema: String,
    pub name: String,
    pub options: SequenceOptions,
}

impl SequenceSpec {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            schema: "public".into(),
            name: name.into(),
            options: SequenceOptions::default(),
        }
    }

    pub fn in_schema(mut self, schema: impl Into<String>) -> Self {
        self.schema = schema.into();
        self
    }

    pub fn options(mut self, options: SequenceOptions) -> Self {
        self.options = options;
        self
    }

    pub fn qualified_name(&self) -> String {
        format!("{}.{}", self.schema, self.name)
    }
}

/// A role declaration.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct RoleSpec {
    pub name: String,
    pub create_db: bool,
    pub create_role: bool,
    pub inherit: bool,
}

impl RoleSpec {
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            create_db: false,
            create_role: false,
            // Postgres roles inherit by default.
            inherit: true,
        }
    }

    pub fn create_db(mut self, on: bool) -> Self {
        self.create_db = on;
        self
    }

    pub fn create_role(mut self, on: bool) -> Self {
        self.create_role = on;
        self
    }

    pub fn inherit(mut self, on: bool) -> Self {
        self.inherit = on;
        self
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders_sql_types() {
        assert_eq!(PgType::Uuid.to_sql_type(), "uuid");
        assert_eq!(PgType::Varchar(Some(255)).to_sql_type(), "varchar(255)");
        assert_eq!(
            PgType::Numeric(Some((10, 2))).to_sql_type(),
            "numeric(10,2)"
        );
        assert_eq!(
            PgType::Array(Box::new(PgType::Text)).to_sql_type(),
            "text[]"
        );
        assert_eq!(PgType::Enum("status".into()).to_sql_type(), "status");
        assert_eq!(PgType::Timestamptz.to_sql_type(), "timestamptz");
        assert_eq!(PgType::Float8.to_sql_type(), "double precision");
        assert_eq!(PgType::Tsvector.to_sql_type(), "tsvector");
        assert_eq!(PgType::Vector(None).to_sql_type(), "vector");
        assert_eq!(PgType::Vector(Some(1536)).to_sql_type(), "vector(1536)");
    }

    #[test]
    fn builder_sets_flags() {
        let c = ColumnSpec::new("x", PgType::Int4)
            .nullable()
            .default_expr("0");
        assert!(c.nullable);
        assert_eq!(c.default.as_deref(), Some("0"));

        let pk = PgTableSpec::new("t", vec![c]).primary_key(["x"]);
        assert_eq!(pk.primary_key, vec!["x".to_string()]);
    }

    #[test]
    fn column_builders_for_generated_identity_unique() {
        let g = ColumnSpec::new("full", PgType::Text).generated_stored("a || b");
        assert_eq!(g.generated.as_ref().unwrap().expression, "a || b");

        let id = ColumnSpec::new("n", PgType::Int8).identity_always();
        assert_eq!(id.identity.as_ref().unwrap().kind, IdentityKind::Always);

        let u = ColumnSpec::new("email", PgType::Text).unique_named("u_email");
        assert_eq!(u.unique.as_ref().unwrap().name.as_deref(), Some("u_email"));
    }

    #[test]
    fn table_builders_collect_constraints() {
        let t = PgTableSpec::new("users", vec![ColumnSpec::new("id", PgType::Uuid)])
            .in_schema("app")
            .primary_key(["id"])
            .foreign_key(
                ForeignKeySpec::new("fk_org", ["org_id"], "public.orgs", ["id"])
                    .on_delete(ReferentialAction::Cascade),
            )
            .unique_constraint(UniqueConstraintSpec::new("u_email", ["email"]))
            .check(CheckConstraintSpec::new("c_pos", "n > 0"))
            .index(IndexSpec::new("idx_email", [IndexColumn::column("email")]).unique())
            .policy(PolicySpec::new("p").for_command(PolicyFor::Select))
            .enable_rls();

        assert_eq!(t.qualified_name(), "app.users");
        assert_eq!(t.foreign_keys.len(), 1);
        assert_eq!(
            t.foreign_keys[0].on_delete,
            Some(ReferentialAction::Cascade)
        );
        assert_eq!(t.unique_constraints.len(), 1);
        assert_eq!(t.check_constraints.len(), 1);
        assert_eq!(t.indexes.len(), 1);
        assert_eq!(t.policies.len(), 1);
        assert!(t.rls_enabled);
    }

    #[test]
    fn top_level_specs_default_to_public() {
        assert_eq!(
            EnumTypeSpec::new("status", ["a", "b"]).qualified_name(),
            "public.status"
        );
        assert_eq!(ViewSpec::new("v", "SELECT 1").qualified_name(), "public.v");
        assert_eq!(SequenceSpec::new("s").qualified_name(), "public.s");
        let r = RoleSpec::new("app").create_db(true);
        assert!(r.create_db && r.inherit);
    }
}
