//! Corpus category: `identity` — `GENERATED { ALWAYS | BY DEFAULT } AS IDENTITY`
//! columns (create / drop / alter). A conformance corpus of identity-column
//! schema-diff scenarios.
//!
//! Mapping notes:
//! - an identity column declaration
//!   → a `public.users` table with a `SnapColumn::new("id", "integer")` carrying a
//!   `SnapIdentity`. Identity columns are marked `notNull: true`, so each gets
//!   `.not_null()`.
//! - `generatedByDefaultAsIdentity()` → [`SnapIdentity::by_default`];
//!   `generatedAlwaysAsIdentity()` → [`SnapIdentity::always`]. Numeric params
//!   (`increment`, `minValue`, `maxValue`, `startWith`, `cache`) are stored as
//!   strings on the snapshot; absent params stay `None` (the differ fills the
//!   Postgres defaults: INCREMENT 1, MINVALUE 1, MAXVALUE 2147483647, START 1,
//!   CACHE 1).
//! - the asserted statement output is the contract, copied into `expected_sql`.
//! - a `{ name: 'custom_seq' }` option sets a custom identity *sequence name*,
//!   carried on [`SnapIdentity::name`] and rendered inline (`sequence name
//!   "custom_seq"`). Absent, the differ derives the Postgres-implicit
//!   `{table}_{column}_seq`.
//! - When `startWith` is omitted, Postgres defaults the sequence
//!   start to `minValue` (then `1`) — see case "all params" below where
//!   `minValue: 3` yields `START WITH 3` with no explicit start.

use postgres_kit::differ::ir::*;

use super::{DiffCase, Status};

/// An empty schema (`from = {}` / `to = {}`).
fn empty() -> SchemaSnapshot {
    SchemaSnapshot::builder().build()
}

/// A `public.users` table with a single `id integer` column carrying `identity`.
fn users(id_identity: SnapIdentity) -> SchemaSnapshot {
    SchemaSnapshot::builder()
        .table(
            SnapTable::new("users").col(
                SnapColumn::new("id", "integer")
                    .not_null()
                    .identity(id_identity),
            ),
        )
        .build()
}

/// A `public.users` table with a plain (non-identity) `id integer` column.
fn users_plain() -> SchemaSnapshot {
    SchemaSnapshot::builder()
        .table(SnapTable::new("users").col(SnapColumn::new("id", "integer")))
        .build()
}

pub fn cases() -> Vec<DiffCase> {
    vec![
        // 1. create table: identity by default - no params
        DiffCase {
            name: "create table: identity by default - no params",
            from: empty(),
            to: users(SnapIdentity::by_default()),
            renames: &[],
            expected_sql: &[
                "CREATE TABLE \"users\" (\n\t\"id\" integer GENERATED BY DEFAULT AS IDENTITY (sequence name \"users_id_seq\" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1)\n);\n",
            ],
            status: Status::Supported,
        },
        // 2. create table: identity by default - few params (custom_seq)
        DiffCase {
            name: "create table: identity by default - few params",
            from: empty(),
            to: users(SnapIdentity {
                name: Some("custom_seq".into()),
                increment: Some("4".into()),
                ..SnapIdentity::by_default()
            }),
            renames: &[],
            expected_sql: &[
                "CREATE TABLE \"users\" (\n\t\"id\" integer GENERATED BY DEFAULT AS IDENTITY (sequence name \"custom_seq\" INCREMENT BY 4 MINVALUE 1 MAXVALUE 2147483647 START WITH 1 CACHE 1)\n);\n",
            ],
            status: Status::Supported,
        },
        // 3. create table: identity by default - all params (custom_seq)
        DiffCase {
            name: "create table: identity by default - all params",
            from: empty(),
            to: users(SnapIdentity {
                name: Some("custom_seq".into()),
                increment: Some("4".into()),
                min_value: Some("3".into()),
                max_value: Some("1000".into()),
                cache: Some("200".into()),
                ..SnapIdentity::by_default()
            }),
            renames: &[],
            expected_sql: &[
                "CREATE TABLE \"users\" (\n\t\"id\" integer GENERATED BY DEFAULT AS IDENTITY (sequence name \"custom_seq\" INCREMENT BY 4 MINVALUE 3 MAXVALUE 1000 START WITH 3 CACHE 200)\n);\n",
            ],
            status: Status::Supported,
        },
        // 4. no diff: identity by default - no params
        DiffCase {
            name: "no diff: identity by default - no params",
            from: users(SnapIdentity::by_default()),
            to: users(SnapIdentity::by_default()),
            renames: &[],
            expected_sql: &[],
            status: Status::Supported,
        },
        // 5. no diff: identity by default - few params
        DiffCase {
            name: "no diff: identity by default - few params",
            from: users(SnapIdentity {
                increment: Some("4".into()),
                ..SnapIdentity::by_default()
            }),
            to: users(SnapIdentity {
                increment: Some("4".into()),
                ..SnapIdentity::by_default()
            }),
            renames: &[],
            expected_sql: &[],
            status: Status::Supported,
        },
        // 6. no diff: identity by default - all params
        DiffCase {
            name: "no diff: identity by default - all params",
            from: users(SnapIdentity {
                increment: Some("4".into()),
                min_value: Some("3".into()),
                max_value: Some("1000".into()),
                cache: Some("200".into()),
                ..SnapIdentity::by_default()
            }),
            to: users(SnapIdentity {
                increment: Some("4".into()),
                min_value: Some("3".into()),
                max_value: Some("1000".into()),
                cache: Some("200".into()),
                ..SnapIdentity::by_default()
            }),
            renames: &[],
            expected_sql: &[],
            status: Status::Supported,
        },
        // 7. drop identity from a column - no params
        DiffCase {
            name: "drop identity from a column - no params",
            from: users(SnapIdentity::by_default()),
            to: users_plain(),
            renames: &[],
            expected_sql: &["ALTER TABLE \"users\" ALTER COLUMN \"id\" DROP IDENTITY;"],
            status: Status::Supported,
        },
        // 8. drop identity from a column - few params
        DiffCase {
            name: "drop identity from a column - few params",
            from: users(SnapIdentity {
                start_with: Some("100".into()),
                increment: Some("3".into()),
                ..SnapIdentity::by_default()
            }),
            to: users_plain(),
            renames: &[],
            expected_sql: &["ALTER TABLE \"users\" ALTER COLUMN \"id\" DROP IDENTITY;"],
            status: Status::Supported,
        },
        // 9. drop identity from a column - all params
        DiffCase {
            name: "drop identity from a column - all params",
            from: users(SnapIdentity {
                start_with: Some("100".into()),
                increment: Some("3".into()),
                cache: Some("100".into()),
                cycle: true,
                ..SnapIdentity::by_default()
            }),
            to: users_plain(),
            renames: &[],
            expected_sql: &["ALTER TABLE \"users\" ALTER COLUMN \"id\" DROP IDENTITY;"],
            status: Status::Supported,
        },
        // 10. alter identity from a column - no params (add startWith)
        DiffCase {
            name: "alter identity from a column - no params",
            from: users(SnapIdentity::by_default()),
            to: users(SnapIdentity {
                start_with: Some("100".into()),
                ..SnapIdentity::by_default()
            }),
            renames: &[],
            expected_sql: &["ALTER TABLE \"users\" ALTER COLUMN \"id\" SET START WITH 100;"],
            status: Status::Supported,
        },
        // 11. alter identity from a column - few params (add cache)
        DiffCase {
            name: "alter identity from a column - few params",
            from: users(SnapIdentity {
                start_with: Some("100".into()),
                ..SnapIdentity::by_default()
            }),
            to: users(SnapIdentity {
                start_with: Some("100".into()),
                cache: Some("10".into()),
                ..SnapIdentity::by_default()
            }),
            renames: &[],
            expected_sql: &["ALTER TABLE \"users\" ALTER COLUMN \"id\" SET CACHE 10;"],
            status: Status::Supported,
        },
        // 12. alter identity from a column - by default to always
        DiffCase {
            name: "alter identity from a column - by default to always",
            from: users(SnapIdentity::by_default()),
            to: users(SnapIdentity {
                start_with: Some("100".into()),
                cache: Some("10".into()),
                ..SnapIdentity::always()
            }),
            renames: &[],
            expected_sql: &[
                "ALTER TABLE \"users\" ALTER COLUMN \"id\" SET GENERATED ALWAYS;",
                "ALTER TABLE \"users\" ALTER COLUMN \"id\" SET START WITH 100;",
                "ALTER TABLE \"users\" ALTER COLUMN \"id\" SET CACHE 10;",
            ],
            status: Status::Supported,
        },
        // 13. alter identity from a column - always to by default
        DiffCase {
            name: "alter identity from a column - always to by default",
            from: users(SnapIdentity::always()),
            to: users(SnapIdentity {
                start_with: Some("100".into()),
                cache: Some("10".into()),
                ..SnapIdentity::by_default()
            }),
            renames: &[],
            expected_sql: &[
                "ALTER TABLE \"users\" ALTER COLUMN \"id\" SET GENERATED BY DEFAULT;",
                "ALTER TABLE \"users\" ALTER COLUMN \"id\" SET START WITH 100;",
                "ALTER TABLE \"users\" ALTER COLUMN \"id\" SET CACHE 10;",
            ],
            status: Status::Supported,
        },
    ]
}
